#pragma once

// incbin fuckery
#ifdef _MSC_VER
#define STARWAY_MSVC
#pragma push_macro("_MSC_VER")
#undef _MSC_VER
#endif

#include <span>

#include "../incbin.h"
#include "../utils.hpp"

// batch_positions.bin is generated by the Montyformat to Starway format converter
INCBIN(BatchPositions, "batch_positions.bin");

// clang-format off

// Indexing this span returns the position of that batch in the data file
const std::span<const size_t> BATCH_POSITIONS {
    reinterpret_cast<const size_t*>(gBatchPositionsData),
    gBatchPositionsSize / sizeof(size_t)
};

// clang-format on

constexpr size_t MAX_PIECES = 32;
constexpr size_t MAX_LEGAL_MOVES = 218;

struct Batch {
   public:
    i16* activeFeaturesStm;
    i16* activeFeaturesNtm;

    i16* stmScores;
    float* stmWDLs;

    std::size_t totalLegalMoves;
    i16* legalMovesIdx;
    u8* visits;

    constexpr Batch(const std::size_t batchSize) {
        this->activeFeaturesStm = new i16[batchSize * MAX_PIECES];
        this->activeFeaturesNtm = new i16[batchSize * MAX_PIECES];

        this->stmScores = new i16[batchSize];
        this->stmWDLs = new float[batchSize];

        this->totalLegalMoves = 0;
        this->legalMovesIdx = new i16[batchSize * MAX_LEGAL_MOVES];
        this->visits = new u8[batchSize * MAX_LEGAL_MOVES];
    }

};  // struct Batch
