#pragma once

// incbin fuckery
#ifdef _MSC_VER
#define STARWAY_MSVC
#pragma push_macro("_MSC_VER")
#undef _MSC_VER
#endif

#include <span>

#include "../incbin.h"
#include "../utils.hpp"

// batch_positions.bin is generated by the Montyformat to Starway format converter
INCBIN(BatchPositions, "batch_positions.bin");

// clang-format off

// Indexing this span returns the position of that batch in the data file
const std::span<const size_t> BATCH_POSITIONS {
    reinterpret_cast<const size_t*>(gBatchPositionsData),
    gBatchPositionsSize / sizeof(size_t)
};

// clang-format on

constexpr size_t MAX_PIECES = 32;
constexpr size_t MAX_LEGAL_MOVES = 256;
constexpr size_t POLICY_OUTPUT_SIZE = 1882;

// A batch of N data entries
struct Batch {
   public:
    // Dataloader will initialize all elements to -1 (no piece) then fill these arrays
    i16* activeFeaturesStm;
    i16* activeFeaturesNtm;

    // 1 per data entry
    i16* stmScores;
    float* stmWDLs;

    // legalMovesIdx stores pairs (entryIdx, moveIdx) sequentially
    // Move index is its index in the output layer
    std::size_t totalLegalMoves;
    std::size_t* legalMovesIdx;

    // The target logits are just the visits distribution of that position
    u8* logits;

    constexpr Batch(const std::size_t batchSize) {
        this->activeFeaturesStm = new i16[batchSize * MAX_PIECES];
        this->activeFeaturesNtm = new i16[batchSize * MAX_PIECES];

        this->stmScores = new i16[batchSize];
        this->stmWDLs = new float[batchSize];

        this->totalLegalMoves = 0;
        this->legalMovesIdx = new std::size_t[batchSize * MAX_LEGAL_MOVES * 2];

        this->logits = new u8[batchSize * POLICY_OUTPUT_SIZE];
    }

};  // struct Batch
